apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lja2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lja2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lja2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lja2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lja2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qgnf-tenant/rhtap-demo-app/hacbs-test-project-lja2@sha256:160170a470faf0a3f7de6143274d24a924b3a0fce18ff3bbc93993ea9baa9e1b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
